//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboScout.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RoboScout.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string StringGrial {
            get {
                return ResourceManager.GetString("StringGrial", resourceCulture);
            }
        }
        
        internal static string StringUIKIT {
            get {
                return ResourceManager.GetString("StringUIKIT", resourceCulture);
            }
        }
        
        internal static string StringColon {
            get {
                return ResourceManager.GetString("StringColon", resourceCulture);
            }
        }
        
        internal static string StringNew {
            get {
                return ResourceManager.GetString("StringNew", resourceCulture);
            }
        }
        
        internal static string StringOK {
            get {
                return ResourceManager.GetString("StringOK", resourceCulture);
            }
        }
        
        internal static string StringSave {
            get {
                return ResourceManager.GetString("StringSave", resourceCulture);
            }
        }
        
        internal static string StringCompare {
            get {
                return ResourceManager.GetString("StringCompare", resourceCulture);
            }
        }
        
        internal static string StringShare {
            get {
                return ResourceManager.GetString("StringShare", resourceCulture);
            }
        }
        
        internal static string StringBuy {
            get {
                return ResourceManager.GetString("StringBuy", resourceCulture);
            }
        }
        
        internal static string StringUsername {
            get {
                return ResourceManager.GetString("StringUsername", resourceCulture);
            }
        }
        
        internal static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        internal static string StringLastName {
            get {
                return ResourceManager.GetString("StringLastName", resourceCulture);
            }
        }
        
        internal static string StringCardNumber {
            get {
                return ResourceManager.GetString("StringCardNumber", resourceCulture);
            }
        }
        
        internal static string StringCVC {
            get {
                return ResourceManager.GetString("StringCVC", resourceCulture);
            }
        }
        
        internal static string StringExpirationDate {
            get {
                return ResourceManager.GetString("StringExpirationDate", resourceCulture);
            }
        }
        
        internal static string StringAddress {
            get {
                return ResourceManager.GetString("StringAddress", resourceCulture);
            }
        }
        
        internal static string StringAddress1 {
            get {
                return ResourceManager.GetString("StringAddress1", resourceCulture);
            }
        }
        
        internal static string StringAddress2 {
            get {
                return ResourceManager.GetString("StringAddress2", resourceCulture);
            }
        }
        
        internal static string StringCity {
            get {
                return ResourceManager.GetString("StringCity", resourceCulture);
            }
        }
        
        internal static string StringState {
            get {
                return ResourceManager.GetString("StringState", resourceCulture);
            }
        }
        
        internal static string StringZipCode {
            get {
                return ResourceManager.GetString("StringZipCode", resourceCulture);
            }
        }
        
        internal static string StringCountry {
            get {
                return ResourceManager.GetString("StringCountry", resourceCulture);
            }
        }
        
        internal static string StringEmail {
            get {
                return ResourceManager.GetString("StringEmail", resourceCulture);
            }
        }
        
        internal static string StringPassword {
            get {
                return ResourceManager.GetString("StringPassword", resourceCulture);
            }
        }
        
        internal static string StringSignUp {
            get {
                return ResourceManager.GetString("StringSignUp", resourceCulture);
            }
        }
        
        internal static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        internal static string StringWelcomeToGrial {
            get {
                return ResourceManager.GetString("StringWelcomeToGrial", resourceCulture);
            }
        }
        
        internal static string StringTwitter {
            get {
                return ResourceManager.GetString("StringTwitter", resourceCulture);
            }
        }
        
        internal static string StringFacebook {
            get {
                return ResourceManager.GetString("StringFacebook", resourceCulture);
            }
        }
        
        internal static string StringSend {
            get {
                return ResourceManager.GetString("StringSend", resourceCulture);
            }
        }
        
        internal static string StringDone {
            get {
                return ResourceManager.GetString("StringDone", resourceCulture);
            }
        }
        
        internal static string StringCantReachLocation {
            get {
                return ResourceManager.GetString("StringCantReachLocation", resourceCulture);
            }
        }
        
        internal static string StringConfirmation {
            get {
                return ResourceManager.GetString("StringConfirmation", resourceCulture);
            }
        }
        
        internal static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        internal static string StringNotification {
            get {
                return ResourceManager.GetString("StringNotification", resourceCulture);
            }
        }
        
        internal static string StringPleaseConfirmAddress {
            get {
                return ResourceManager.GetString("StringPleaseConfirmAddress", resourceCulture);
            }
        }
        
        internal static string StringPleaseContactSupport {
            get {
                return ResourceManager.GetString("StringPleaseContactSupport", resourceCulture);
            }
        }
        
        internal static string StringSuccess {
            get {
                return ResourceManager.GetString("StringSuccess", resourceCulture);
            }
        }
        
        internal static string StringWarning {
            get {
                return ResourceManager.GetString("StringWarning", resourceCulture);
            }
        }
        
        internal static string StringYouHaveANewFollower {
            get {
                return ResourceManager.GetString("StringYouHaveANewFollower", resourceCulture);
            }
        }
        
        internal static string StringYouHaveANewMessage {
            get {
                return ResourceManager.GetString("StringYouHaveANewMessage", resourceCulture);
            }
        }
        
        internal static string StringScreens {
            get {
                return ResourceManager.GetString("StringScreens", resourceCulture);
            }
        }
        
        internal static string StringCategorySocial {
            get {
                return ResourceManager.GetString("StringCategorySocial", resourceCulture);
            }
        }
        
        internal static string StringCategoryArticles {
            get {
                return ResourceManager.GetString("StringCategoryArticles", resourceCulture);
            }
        }
        
        internal static string StringCategoryDashboards {
            get {
                return ResourceManager.GetString("StringCategoryDashboards", resourceCulture);
            }
        }
        
        internal static string StringCategoryNavigation {
            get {
                return ResourceManager.GetString("StringCategoryNavigation", resourceCulture);
            }
        }
        
        internal static string StringCategoryLogins {
            get {
                return ResourceManager.GetString("StringCategoryLogins", resourceCulture);
            }
        }
        
        internal static string StringCategoryECommerce {
            get {
                return ResourceManager.GetString("StringCategoryECommerce", resourceCulture);
            }
        }
        
        internal static string StringCategoryWalkthroughs {
            get {
                return ResourceManager.GetString("StringCategoryWalkthroughs", resourceCulture);
            }
        }
        
        internal static string StringCategoryMessages {
            get {
                return ResourceManager.GetString("StringCategoryMessages", resourceCulture);
            }
        }
        
        internal static string StringCategoryTheme {
            get {
                return ResourceManager.GetString("StringCategoryTheme", resourceCulture);
            }
        }
        
        internal static string StringRichardStainford {
            get {
                return ResourceManager.GetString("StringRichardStainford", resourceCulture);
            }
        }
        
        internal static string StringClareJapi {
            get {
                return ResourceManager.GetString("StringClareJapi", resourceCulture);
            }
        }
        
        internal static string StringRobertStainford {
            get {
                return ResourceManager.GetString("StringRobertStainford", resourceCulture);
            }
        }
        
        internal static string StringNext {
            get {
                return ResourceManager.GetString("StringNext", resourceCulture);
            }
        }
        
        internal static string StringPrevious {
            get {
                return ResourceManager.GetString("StringPrevious", resourceCulture);
            }
        }
        
        internal static string StringFinish {
            get {
                return ResourceManager.GetString("StringFinish", resourceCulture);
            }
        }
        
        internal static string StringGiveUsACall {
            get {
                return ResourceManager.GetString("StringGiveUsACall", resourceCulture);
            }
        }
        
        internal static string StringLinkedin {
            get {
                return ResourceManager.GetString("StringLinkedin", resourceCulture);
            }
        }
        
        internal static string StringApply {
            get {
                return ResourceManager.GetString("StringApply", resourceCulture);
            }
        }
        
        internal static string StringCustom {
            get {
                return ResourceManager.GetString("StringCustom", resourceCulture);
            }
        }
        
        internal static string StringCallTheExperts {
            get {
                return ResourceManager.GetString("StringCallTheExperts", resourceCulture);
            }
        }
        
        internal static string StringContact {
            get {
                return ResourceManager.GetString("StringContact", resourceCulture);
            }
        }
        
        internal static string StringLight {
            get {
                return ResourceManager.GetString("StringLight", resourceCulture);
            }
        }
        
        internal static string StringDark {
            get {
                return ResourceManager.GetString("StringDark", resourceCulture);
            }
        }
        
        internal static string StringEnterprise {
            get {
                return ResourceManager.GetString("StringEnterprise", resourceCulture);
            }
        }
        
        internal static string StringLightTheme {
            get {
                return ResourceManager.GetString("StringLightTheme", resourceCulture);
            }
        }
        
        internal static string StringDarkTheme {
            get {
                return ResourceManager.GetString("StringDarkTheme", resourceCulture);
            }
        }
        
        internal static string StringEnterpriseTheme {
            get {
                return ResourceManager.GetString("StringEnterpriseTheme", resourceCulture);
            }
        }
        
        internal static string StringLoading {
            get {
                return ResourceManager.GetString("StringLoading", resourceCulture);
            }
        }
        
        internal static string StringSaveChanges {
            get {
                return ResourceManager.GetString("StringSaveChanges", resourceCulture);
            }
        }
        
        internal static string StringBatmanChoice {
            get {
                return ResourceManager.GetString("StringBatmanChoice", resourceCulture);
            }
        }
        
        internal static string StringExtraSoftUIFlavor {
            get {
                return ResourceManager.GetString("StringExtraSoftUIFlavor", resourceCulture);
            }
        }
        
        internal static string StringImpressYourBoss {
            get {
                return ResourceManager.GetString("StringImpressYourBoss", resourceCulture);
            }
        }
        
        internal static string StringIcons {
            get {
                return ResourceManager.GetString("StringIcons", resourceCulture);
            }
        }
        
        internal static string StringContextActionTapped {
            get {
                return ResourceManager.GetString("StringContextActionTapped", resourceCulture);
            }
        }
        
        internal static string StringTappedOnContextAction {
            get {
                return ResourceManager.GetString("StringTappedOnContextAction", resourceCulture);
            }
        }
        
        internal static string StringMessageTapped {
            get {
                return ResourceManager.GetString("StringMessageTapped", resourceCulture);
            }
        }
        
        internal static string StringTappedOnAuthorMessage {
            get {
                return ResourceManager.GetString("StringTappedOnAuthorMessage", resourceCulture);
            }
        }
        
        internal static string StringMoreFrom {
            get {
                return ResourceManager.GetString("StringMoreFrom", resourceCulture);
            }
        }
        
        internal static string PageTitleArticleClassicView {
            get {
                return ResourceManager.GetString("PageTitleArticleClassicView", resourceCulture);
            }
        }
        
        internal static string PageTitleArticlesFeed {
            get {
                return ResourceManager.GetString("PageTitleArticlesFeed", resourceCulture);
            }
        }
        
        internal static string PageTitleArticleList {
            get {
                return ResourceManager.GetString("PageTitleArticleList", resourceCulture);
            }
        }
        
        internal static string PageTitleArticlesListVariant {
            get {
                return ResourceManager.GetString("PageTitleArticlesListVariant", resourceCulture);
            }
        }
        
        internal static string PageTitleFrontPageNews {
            get {
                return ResourceManager.GetString("PageTitleFrontPageNews", resourceCulture);
            }
        }
        
        internal static string PageTitleArticleView {
            get {
                return ResourceManager.GetString("PageTitleArticleView", resourceCulture);
            }
        }
        
        internal static string PageTitleDashboardCards {
            get {
                return ResourceManager.GetString("PageTitleDashboardCards", resourceCulture);
            }
        }
        
        internal static string PageTitleDashboardFlat {
            get {
                return ResourceManager.GetString("PageTitleDashboardFlat", resourceCulture);
            }
        }
        
        internal static string PageTitleDashboardMultipleScroll {
            get {
                return ResourceManager.GetString("PageTitleDashboardMultipleScroll", resourceCulture);
            }
        }
        
        internal static string PageTitleDashboardMultipleTiles {
            get {
                return ResourceManager.GetString("PageTitleDashboardMultipleTiles", resourceCulture);
            }
        }
        
        internal static string PageMenuTitleDashboardIcons {
            get {
                return ResourceManager.GetString("PageMenuTitleDashboardIcons", resourceCulture);
            }
        }
        
        internal static string PageTitleDashboardIcons {
            get {
                return ResourceManager.GetString("PageTitleDashboardIcons", resourceCulture);
            }
        }
        
        internal static string PageTitleDashboardWithImages {
            get {
                return ResourceManager.GetString("PageTitleDashboardWithImages", resourceCulture);
            }
        }
        
        internal static string PageTitleDashboardScrollable {
            get {
                return ResourceManager.GetString("PageTitleDashboardScrollable", resourceCulture);
            }
        }
        
        internal static string PageTitleMovieSelection {
            get {
                return ResourceManager.GetString("PageTitleMovieSelection", resourceCulture);
            }
        }
        
        internal static string RoundedLabelCast {
            get {
                return ResourceManager.GetString("RoundedLabelCast", resourceCulture);
            }
        }
        
        internal static string RoundedLabelDirector {
            get {
                return ResourceManager.GetString("RoundedLabelDirector", resourceCulture);
            }
        }
        
        internal static string AlertTitleMovieTapped {
            get {
                return ResourceManager.GetString("AlertTitleMovieTapped", resourceCulture);
            }
        }
        
        internal static string AlertMessageMovieShouldPlayMovieNow {
            get {
                return ResourceManager.GetString("AlertMessageMovieShouldPlayMovieNow", resourceCulture);
            }
        }
        
        internal static string SampleDashboardGrialMovies {
            get {
                return ResourceManager.GetString("SampleDashboardGrialMovies", resourceCulture);
            }
        }
        
        internal static string ButtonPlayMovie {
            get {
                return ResourceManager.GetString("ButtonPlayMovie", resourceCulture);
            }
        }
        
        internal static string PageTitleDocumentTimeline {
            get {
                return ResourceManager.GetString("PageTitleDocumentTimeline", resourceCulture);
            }
        }
        
        internal static string PageTitleProfile {
            get {
                return ResourceManager.GetString("PageTitleProfile", resourceCulture);
            }
        }
        
        internal static string LabelPassionDrivenDesigner {
            get {
                return ResourceManager.GetString("LabelPassionDrivenDesigner", resourceCulture);
            }
        }
        
        internal static string LabelPhotographyIsMyPassion {
            get {
                return ResourceManager.GetString("LabelPhotographyIsMyPassion", resourceCulture);
            }
        }
        
        internal static string SampleUserProfile {
            get {
                return ResourceManager.GetString("SampleUserProfile", resourceCulture);
            }
        }
        
        internal static string PageTitleSocial {
            get {
                return ResourceManager.GetString("PageTitleSocial", resourceCulture);
            }
        }
        
        internal static string PageTitleSocialVariant {
            get {
                return ResourceManager.GetString("PageTitleSocialVariant", resourceCulture);
            }
        }
        
        internal static string LabelUserDescriptionVariant {
            get {
                return ResourceManager.GetString("LabelUserDescriptionVariant", resourceCulture);
            }
        }
        
        internal static string PageTitleTimeline {
            get {
                return ResourceManager.GetString("PageTitleTimeline", resourceCulture);
            }
        }
        
        internal static string StringFriends {
            get {
                return ResourceManager.GetString("StringFriends", resourceCulture);
            }
        }
        
        internal static string StringPhotos {
            get {
                return ResourceManager.GetString("StringPhotos", resourceCulture);
            }
        }
        
        internal static string ButtonAddToCart {
            get {
                return ResourceManager.GetString("ButtonAddToCart", resourceCulture);
            }
        }
        
        internal static string PageTitleProductsCatalog {
            get {
                return ResourceManager.GetString("PageTitleProductsCatalog", resourceCulture);
            }
        }
        
        internal static string SampleProductFullscreen {
            get {
                return ResourceManager.GetString("SampleProductFullscreen", resourceCulture);
            }
        }
        
        internal static string PageTitleProductOrder {
            get {
                return ResourceManager.GetString("PageTitleProductOrder", resourceCulture);
            }
        }
        
        internal static string PageTitleProductGrid {
            get {
                return ResourceManager.GetString("PageTitleProductGrid", resourceCulture);
            }
        }
        
        internal static string PageTitleProductGridVariant {
            get {
                return ResourceManager.GetString("PageTitleProductGridVariant", resourceCulture);
            }
        }
        
        internal static string BannerTitle25DiscOff {
            get {
                return ResourceManager.GetString("BannerTitle25DiscOff", resourceCulture);
            }
        }
        
        internal static string BannerBodyEnjoyItNow {
            get {
                return ResourceManager.GetString("BannerBodyEnjoyItNow", resourceCulture);
            }
        }
        
        internal static string SampleProductItemView {
            get {
                return ResourceManager.GetString("SampleProductItemView", resourceCulture);
            }
        }
        
        internal static string SampleProductCarousel {
            get {
                return ResourceManager.GetString("SampleProductCarousel", resourceCulture);
            }
        }
        
        internal static string PageTitleSimpleLogin {
            get {
                return ResourceManager.GetString("PageTitleSimpleLogin", resourceCulture);
            }
        }
        
        internal static string PageTitleSimpleSignup {
            get {
                return ResourceManager.GetString("PageTitleSimpleSignup", resourceCulture);
            }
        }
        
        internal static string PageTitlePasswordRecovery {
            get {
                return ResourceManager.GetString("PageTitlePasswordRecovery", resourceCulture);
            }
        }
        
        internal static string PageTitleLogin {
            get {
                return ResourceManager.GetString("PageTitleLogin", resourceCulture);
            }
        }
        
        internal static string PageTitleSignup {
            get {
                return ResourceManager.GetString("PageTitleSignup", resourceCulture);
            }
        }
        
        internal static string LabelUseCredentialsToLogin {
            get {
                return ResourceManager.GetString("LabelUseCredentialsToLogin", resourceCulture);
            }
        }
        
        internal static string LabelOrConnectWith {
            get {
                return ResourceManager.GetString("LabelOrConnectWith", resourceCulture);
            }
        }
        
        internal static string LabelForgotYourPassword {
            get {
                return ResourceManager.GetString("LabelForgotYourPassword", resourceCulture);
            }
        }
        
        internal static string LabelForgotYourPasswordExplained {
            get {
                return ResourceManager.GetString("LabelForgotYourPasswordExplained", resourceCulture);
            }
        }
        
        internal static string ErrorPleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("ErrorPleaseEnterValidEmail", resourceCulture);
            }
        }
        
        internal static string LabelLoginOrRegisterUsinMailOrPass {
            get {
                return ResourceManager.GetString("LabelLoginOrRegisterUsinMailOrPass", resourceCulture);
            }
        }
        
        internal static string LabelRegisterNow {
            get {
                return ResourceManager.GetString("LabelRegisterNow", resourceCulture);
            }
        }
        
        internal static string LabelRegisterNowAndEnjoy {
            get {
                return ResourceManager.GetString("LabelRegisterNowAndEnjoy", resourceCulture);
            }
        }
        
        internal static string LabelPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("LabelPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        internal static string LabelRepeatPassword {
            get {
                return ResourceManager.GetString("LabelRepeatPassword", resourceCulture);
            }
        }
        
        internal static string ButtonAlreadyUserLoginNow {
            get {
                return ResourceManager.GetString("ButtonAlreadyUserLoginNow", resourceCulture);
            }
        }
        
        internal static string PageTitleChatTimeLine {
            get {
                return ResourceManager.GetString("PageTitleChatTimeLine", resourceCulture);
            }
        }
        
        internal static string PageTitleRecentChatList {
            get {
                return ResourceManager.GetString("PageTitleRecentChatList", resourceCulture);
            }
        }
        
        internal static string PageTitleMessages {
            get {
                return ResourceManager.GetString("PageTitleMessages", resourceCulture);
            }
        }
        
        internal static string PageTitleChatMessageList {
            get {
                return ResourceManager.GetString("PageTitleChatMessageList", resourceCulture);
            }
        }
        
        internal static string LabelThereIsNothingHere {
            get {
                return ResourceManager.GetString("LabelThereIsNothingHere", resourceCulture);
            }
        }
        
        internal static string PageTitleMainMenu {
            get {
                return ResourceManager.GetString("PageTitleMainMenu", resourceCulture);
            }
        }
        
        internal static string PageTitleCardsList {
            get {
                return ResourceManager.GetString("PageTitleCardsList", resourceCulture);
            }
        }
        
        internal static string PageTitleCategoriesListFlat {
            get {
                return ResourceManager.GetString("PageTitleCategoriesListFlat", resourceCulture);
            }
        }
        
        internal static string PageTitleCategoriesListWithIcons {
            get {
                return ResourceManager.GetString("PageTitleCategoriesListWithIcons", resourceCulture);
            }
        }
        
        internal static string PageTitleCategoryListImages {
            get {
                return ResourceManager.GetString("PageTitleCategoryListImages", resourceCulture);
            }
        }
        
        internal static string PageTitleEmptyState {
            get {
                return ResourceManager.GetString("PageTitleEmptyState", resourceCulture);
            }
        }
        
        internal static string PageTitleTitleNotifications {
            get {
                return ResourceManager.GetString("PageTitleTitleNotifications", resourceCulture);
            }
        }
        
        internal static string StringReadyMadeUIsForXamarin {
            get {
                return ResourceManager.GetString("StringReadyMadeUIsForXamarin", resourceCulture);
            }
        }
        
        internal static string PageTitleWelcome {
            get {
                return ResourceManager.GetString("PageTitleWelcome", resourceCulture);
            }
        }
        
        internal static string LabelTakeYourAppToNextLevel {
            get {
                return ResourceManager.GetString("LabelTakeYourAppToNextLevel", resourceCulture);
            }
        }
        
        internal static string PageTitleWelcomeStarter {
            get {
                return ResourceManager.GetString("PageTitleWelcomeStarter", resourceCulture);
            }
        }
        
        internal static string PageTitleCustomNavBar {
            get {
                return ResourceManager.GetString("PageTitleCustomNavBar", resourceCulture);
            }
        }
        
        internal static string SampleTitleRootPage {
            get {
                return ResourceManager.GetString("SampleTitleRootPage", resourceCulture);
            }
        }
        
        internal static string LabelWelcomeToGrialStarter {
            get {
                return ResourceManager.GetString("LabelWelcomeToGrialStarter", resourceCulture);
            }
        }
        
        internal static string LabelWelcomeToGrialStarterDescription {
            get {
                return ResourceManager.GetString("LabelWelcomeToGrialStarterDescription", resourceCulture);
            }
        }
        
        internal static string ButtonSeeOurWalkThrough {
            get {
                return ResourceManager.GetString("ButtonSeeOurWalkThrough", resourceCulture);
            }
        }
        
        internal static string ButtonBrowseOurSamples {
            get {
                return ResourceManager.GetString("ButtonBrowseOurSamples", resourceCulture);
            }
        }
        
        internal static string SampleTitleWalkthrough {
            get {
                return ResourceManager.GetString("SampleTitleWalkthrough", resourceCulture);
            }
        }
        
        internal static string SampleTitleWalkthroughFlat {
            get {
                return ResourceManager.GetString("SampleTitleWalkthroughFlat", resourceCulture);
            }
        }
        
        internal static string SampleTitleWalkthroughVariant {
            get {
                return ResourceManager.GetString("SampleTitleWalkthroughVariant", resourceCulture);
            }
        }
        
        internal static string WalkthroughHeaderLearn {
            get {
                return ResourceManager.GetString("WalkthroughHeaderLearn", resourceCulture);
            }
        }
        
        internal static string WalkthroughHeaderSaveTime {
            get {
                return ResourceManager.GetString("WalkthroughHeaderSaveTime", resourceCulture);
            }
        }
        
        internal static string WalkthroughHeaderWelcome {
            get {
                return ResourceManager.GetString("WalkthroughHeaderWelcome", resourceCulture);
            }
        }
        
        internal static string WalkthroughTextLearn {
            get {
                return ResourceManager.GetString("WalkthroughTextLearn", resourceCulture);
            }
        }
        
        internal static string WalkthroughTextSaveTime {
            get {
                return ResourceManager.GetString("WalkthroughTextSaveTime", resourceCulture);
            }
        }
        
        internal static string WalkthroughTextWelcome {
            get {
                return ResourceManager.GetString("WalkthroughTextWelcome", resourceCulture);
            }
        }
        
        internal static string PageTitleAnimation {
            get {
                return ResourceManager.GetString("PageTitleAnimation", resourceCulture);
            }
        }
        
        internal static string LabelYesGrialSupportsLottie {
            get {
                return ResourceManager.GetString("LabelYesGrialSupportsLottie", resourceCulture);
            }
        }
        
        internal static string LabelNeedCustomAnimations {
            get {
                return ResourceManager.GetString("LabelNeedCustomAnimations", resourceCulture);
            }
        }
        
        internal static string PageTitleTabControl {
            get {
                return ResourceManager.GetString("PageTitleTabControl", resourceCulture);
            }
        }
        
        internal static string PageTitleAndroidTabControl {
            get {
                return ResourceManager.GetString("PageTitleAndroidTabControl", resourceCulture);
            }
        }
        
        internal static string PageTitleiOSTabControl {
            get {
                return ResourceManager.GetString("PageTitleiOSTabControl", resourceCulture);
            }
        }
        
        internal static string PageTitleBottomTabControl {
            get {
                return ResourceManager.GetString("PageTitleBottomTabControl", resourceCulture);
            }
        }
        
        internal static string PageTitleTabbedPage {
            get {
                return ResourceManager.GetString("PageTitleTabbedPage", resourceCulture);
            }
        }
        
        internal static string SampleTitleThemeDemoSettings {
            get {
                return ResourceManager.GetString("SampleTitleThemeDemoSettings", resourceCulture);
            }
        }
        
        internal static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        internal static string PageTitleCustomSettings {
            get {
                return ResourceManager.GetString("PageTitleCustomSettings", resourceCulture);
            }
        }
        
        internal static string PageTitleCustomActivityIndicator {
            get {
                return ResourceManager.GetString("PageTitleCustomActivityIndicator", resourceCulture);
            }
        }
        
        internal static string PageTitleResponsiveHelpers {
            get {
                return ResourceManager.GetString("PageTitleResponsiveHelpers", resourceCulture);
            }
        }
        
        internal static string PageTitleThemeFontIcons {
            get {
                return ResourceManager.GetString("PageTitleThemeFontIcons", resourceCulture);
            }
        }
        
        internal static string PageTitleNativeControls {
            get {
                return ResourceManager.GetString("PageTitleNativeControls", resourceCulture);
            }
        }
        
        internal static string PageTitleCustomRenderers {
            get {
                return ResourceManager.GetString("PageTitleCustomRenderers", resourceCulture);
            }
        }
        
        internal static string PageTitleCommonViews {
            get {
                return ResourceManager.GetString("PageTitleCommonViews", resourceCulture);
            }
        }
        
        internal static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        internal static string PageTitleWebview {
            get {
                return ResourceManager.GetString("PageTitleWebview", resourceCulture);
            }
        }
        
        internal static string PageTitleThemesPreview {
            get {
                return ResourceManager.GetString("PageTitleThemesPreview", resourceCulture);
            }
        }
        
        internal static string LabelDisplayGlobalIssues {
            get {
                return ResourceManager.GetString("LabelDisplayGlobalIssues", resourceCulture);
            }
        }
        
        internal static string LabelClearImageCache {
            get {
                return ResourceManager.GetString("LabelClearImageCache", resourceCulture);
            }
        }
        
        internal static string LabelActivityIndicators {
            get {
                return ResourceManager.GetString("LabelActivityIndicators", resourceCulture);
            }
        }
        
        internal static string LabelButtons {
            get {
                return ResourceManager.GetString("LabelButtons", resourceCulture);
            }
        }
        
        internal static string LabelFrames {
            get {
                return ResourceManager.GetString("LabelFrames", resourceCulture);
            }
        }
        
        internal static string LabelThisIsAFrameDescription {
            get {
                return ResourceManager.GetString("LabelThisIsAFrameDescription", resourceCulture);
            }
        }
        
        internal static string LabelEntriesAndEditors {
            get {
                return ResourceManager.GetString("LabelEntriesAndEditors", resourceCulture);
            }
        }
        
        internal static string LabelPlaceholderEmail {
            get {
                return ResourceManager.GetString("LabelPlaceholderEmail", resourceCulture);
            }
        }
        
        internal static string EditorSampleText {
            get {
                return ResourceManager.GetString("EditorSampleText", resourceCulture);
            }
        }
        
        internal static string LabelSliders {
            get {
                return ResourceManager.GetString("LabelSliders", resourceCulture);
            }
        }
        
        internal static string LabelProgressBars {
            get {
                return ResourceManager.GetString("LabelProgressBars", resourceCulture);
            }
        }
        
        internal static string LabelSwitches {
            get {
                return ResourceManager.GetString("LabelSwitches", resourceCulture);
            }
        }
        
        internal static string LabelPickers {
            get {
                return ResourceManager.GetString("LabelPickers", resourceCulture);
            }
        }
        
        internal static string PickerTitleSample {
            get {
                return ResourceManager.GetString("PickerTitleSample", resourceCulture);
            }
        }
        
        internal static string LabelListViewAndSearchBar {
            get {
                return ResourceManager.GetString("LabelListViewAndSearchBar", resourceCulture);
            }
        }
        
        internal static string SearchBarPlaceholderSearchForAName {
            get {
                return ResourceManager.GetString("SearchBarPlaceholderSearchForAName", resourceCulture);
            }
        }
        
        internal static string ButtonDefault {
            get {
                return ResourceManager.GetString("ButtonDefault", resourceCulture);
            }
        }
        
        internal static string ButtonPrimaryAction {
            get {
                return ResourceManager.GetString("ButtonPrimaryAction", resourceCulture);
            }
        }
        
        internal static string ButtonSecondaryAction {
            get {
                return ResourceManager.GetString("ButtonSecondaryAction", resourceCulture);
            }
        }
        
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        internal static string ButtonMore {
            get {
                return ResourceManager.GetString("ButtonMore", resourceCulture);
            }
        }
        
        internal static string ButtonAddComment {
            get {
                return ResourceManager.GetString("ButtonAddComment", resourceCulture);
            }
        }
        
        internal static string LabelArtinaButtons {
            get {
                return ResourceManager.GetString("LabelArtinaButtons", resourceCulture);
            }
        }
        
        internal static string LabelCircleImages {
            get {
                return ResourceManager.GetString("LabelCircleImages", resourceCulture);
            }
        }
        
        internal static string LabelArtinaEntry {
            get {
                return ResourceManager.GetString("LabelArtinaEntry", resourceCulture);
            }
        }
        
        internal static string LabelValidationEntryErrorStyle {
            get {
                return ResourceManager.GetString("LabelValidationEntryErrorStyle", resourceCulture);
            }
        }
        
        internal static string StringSomethingWrongHere {
            get {
                return ResourceManager.GetString("StringSomethingWrongHere", resourceCulture);
            }
        }
        
        internal static string ValidationErrorEnterRequiredInfo {
            get {
                return ResourceManager.GetString("ValidationErrorEnterRequiredInfo", resourceCulture);
            }
        }
        
        internal static string ValidationWarningOops {
            get {
                return ResourceManager.GetString("ValidationWarningOops", resourceCulture);
            }
        }
        
        internal static string StringYourAccount {
            get {
                return ResourceManager.GetString("StringYourAccount", resourceCulture);
            }
        }
        
        internal static string StringConnectYourAccount {
            get {
                return ResourceManager.GetString("StringConnectYourAccount", resourceCulture);
            }
        }
        
        internal static string ImageCellDetailDaysLoggedIn {
            get {
                return ResourceManager.GetString("ImageCellDetailDaysLoggedIn", resourceCulture);
            }
        }
        
        internal static string EntryCellSampleEmail {
            get {
                return ResourceManager.GetString("EntryCellSampleEmail", resourceCulture);
            }
        }
        
        internal static string EntryCellPlaceholderPhoneNumber {
            get {
                return ResourceManager.GetString("EntryCellPlaceholderPhoneNumber", resourceCulture);
            }
        }
        
        internal static string LabelCustomNavBar {
            get {
                return ResourceManager.GetString("LabelCustomNavBar", resourceCulture);
            }
        }
        
        internal static string LabelCustomavBarNoteMenu {
            get {
                return ResourceManager.GetString("LabelCustomavBarNoteMenu", resourceCulture);
            }
        }
        
        internal static string LabelCustomNavBarText {
            get {
                return ResourceManager.GetString("LabelCustomNavBarText", resourceCulture);
            }
        }
        
        internal static string LabelBrandBlock {
            get {
                return ResourceManager.GetString("LabelBrandBlock", resourceCulture);
            }
        }
        
        internal static string LabelBadge {
            get {
                return ResourceManager.GetString("LabelBadge", resourceCulture);
            }
        }
        
        internal static string LabelRoundedLabel {
            get {
                return ResourceManager.GetString("LabelRoundedLabel", resourceCulture);
            }
        }
        
        internal static string RoundedLabelTextSample {
            get {
                return ResourceManager.GetString("RoundedLabelTextSample", resourceCulture);
            }
        }
        
        internal static string LabelAboutUsText {
            get {
                return ResourceManager.GetString("LabelAboutUsText", resourceCulture);
            }
        }
        
        internal static string LabelVisualStudioPartner {
            get {
                return ResourceManager.GetString("LabelVisualStudioPartner", resourceCulture);
            }
        }
        
        internal static string LabelVisualStudioPartnerLongText {
            get {
                return ResourceManager.GetString("LabelVisualStudioPartnerLongText", resourceCulture);
            }
        }
        
        internal static string LabelWeAreATeamOfPassionate {
            get {
                return ResourceManager.GetString("LabelWeAreATeamOfPassionate", resourceCulture);
            }
        }
        
        internal static string LabelOurProducts {
            get {
                return ResourceManager.GetString("LabelOurProducts", resourceCulture);
            }
        }
        
        internal static string LabelOurProductsLongText {
            get {
                return ResourceManager.GetString("LabelOurProductsLongText", resourceCulture);
            }
        }
        
        internal static string LabelSpecialThanks {
            get {
                return ResourceManager.GetString("LabelSpecialThanks", resourceCulture);
            }
        }
        
        internal static string LabelCredits {
            get {
                return ResourceManager.GetString("LabelCredits", resourceCulture);
            }
        }
        
        internal static string TabItemTextFriends {
            get {
                return ResourceManager.GetString("TabItemTextFriends", resourceCulture);
            }
        }
        
        internal static string StringHelloClare {
            get {
                return ResourceManager.GetString("StringHelloClare", resourceCulture);
            }
        }
        
        internal static string StringNoPendingTasksToday {
            get {
                return ResourceManager.GetString("StringNoPendingTasksToday", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteAccount {
            get {
                return ResourceManager.GetString("ButtonDeleteAccount", resourceCulture);
            }
        }
        
        internal static string UXDIVERS {
            get {
                return ResourceManager.GetString("UXDIVERS", resourceCulture);
            }
        }
    }
}
