// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RoboScout.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RoboScout.Resx.DataResources", typeof(DataResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string User1Name {
            get {
                return ResourceManager.GetString("User1Name", resourceCulture);
            }
        }
        
        internal static string User2Name {
            get {
                return ResourceManager.GetString("User2Name", resourceCulture);
            }
        }
        
        internal static string User3Name {
            get {
                return ResourceManager.GetString("User3Name", resourceCulture);
            }
        }
        
        internal static string User4Name {
            get {
                return ResourceManager.GetString("User4Name", resourceCulture);
            }
        }
        
        internal static string User5Name {
            get {
                return ResourceManager.GetString("User5Name", resourceCulture);
            }
        }
        
        internal static string User6Name {
            get {
                return ResourceManager.GetString("User6Name", resourceCulture);
            }
        }
        
        internal static string User7Name {
            get {
                return ResourceManager.GetString("User7Name", resourceCulture);
            }
        }
        
        internal static string MainNewsBody {
            get {
                return ResourceManager.GetString("MainNewsBody", resourceCulture);
            }
        }
        
        internal static string Post1Title {
            get {
                return ResourceManager.GetString("Post1Title", resourceCulture);
            }
        }
        
        internal static string Post1SubTitle {
            get {
                return ResourceManager.GetString("Post1SubTitle", resourceCulture);
            }
        }
        
        internal static string Post1Body {
            get {
                return ResourceManager.GetString("Post1Body", resourceCulture);
            }
        }
        
        internal static string PostSectionActuality {
            get {
                return ResourceManager.GetString("PostSectionActuality", resourceCulture);
            }
        }
        
        internal static string PostQuote {
            get {
                return ResourceManager.GetString("PostQuote", resourceCulture);
            }
        }
        
        internal static string Post1When {
            get {
                return ResourceManager.GetString("Post1When", resourceCulture);
            }
        }
        
        internal static string Post2Title {
            get {
                return ResourceManager.GetString("Post2Title", resourceCulture);
            }
        }
        
        internal static string Post2SubTitle {
            get {
                return ResourceManager.GetString("Post2SubTitle", resourceCulture);
            }
        }
        
        internal static string Post2When {
            get {
                return ResourceManager.GetString("Post2When", resourceCulture);
            }
        }
        
        internal static string Post2Body {
            get {
                return ResourceManager.GetString("Post2Body", resourceCulture);
            }
        }
        
        internal static string PostSectionSports {
            get {
                return ResourceManager.GetString("PostSectionSports", resourceCulture);
            }
        }
        
        internal static string Post3Title {
            get {
                return ResourceManager.GetString("Post3Title", resourceCulture);
            }
        }
        
        internal static string Post3SubTitle {
            get {
                return ResourceManager.GetString("Post3SubTitle", resourceCulture);
            }
        }
        
        internal static string Post3When {
            get {
                return ResourceManager.GetString("Post3When", resourceCulture);
            }
        }
        
        internal static string PostSectionFreeTime {
            get {
                return ResourceManager.GetString("PostSectionFreeTime", resourceCulture);
            }
        }
        
        internal static string Post4Title {
            get {
                return ResourceManager.GetString("Post4Title", resourceCulture);
            }
        }
        
        internal static string Post4SubTitle {
            get {
                return ResourceManager.GetString("Post4SubTitle", resourceCulture);
            }
        }
        
        internal static string Post4When {
            get {
                return ResourceManager.GetString("Post4When", resourceCulture);
            }
        }
        
        internal static string PostSectionScience {
            get {
                return ResourceManager.GetString("PostSectionScience", resourceCulture);
            }
        }
        
        internal static string Post5Title {
            get {
                return ResourceManager.GetString("Post5Title", resourceCulture);
            }
        }
        
        internal static string Post5SubTitle {
            get {
                return ResourceManager.GetString("Post5SubTitle", resourceCulture);
            }
        }
        
        internal static string Post5When {
            get {
                return ResourceManager.GetString("Post5When", resourceCulture);
            }
        }
        
        internal static string PostSectionNature {
            get {
                return ResourceManager.GetString("PostSectionNature", resourceCulture);
            }
        }
        
        internal static string Post6Title {
            get {
                return ResourceManager.GetString("Post6Title", resourceCulture);
            }
        }
        
        internal static string Post6SubTitle {
            get {
                return ResourceManager.GetString("Post6SubTitle", resourceCulture);
            }
        }
        
        internal static string Post6When {
            get {
                return ResourceManager.GetString("Post6When", resourceCulture);
            }
        }
        
        internal static string PostSectionHealth {
            get {
                return ResourceManager.GetString("PostSectionHealth", resourceCulture);
            }
        }
        
        internal static string MessageDateMonthAndDay {
            get {
                return ResourceManager.GetString("MessageDateMonthAndDay", resourceCulture);
            }
        }
        
        internal static string MessageDateYesterday {
            get {
                return ResourceManager.GetString("MessageDateYesterday", resourceCulture);
            }
        }
        
        internal static string MessageDateMinutes {
            get {
                return ResourceManager.GetString("MessageDateMinutes", resourceCulture);
            }
        }
        
        internal static string Message1Title {
            get {
                return ResourceManager.GetString("Message1Title", resourceCulture);
            }
        }
        
        internal static string Message2Title {
            get {
                return ResourceManager.GetString("Message2Title", resourceCulture);
            }
        }
        
        internal static string Message3Title {
            get {
                return ResourceManager.GetString("Message3Title", resourceCulture);
            }
        }
        
        internal static string Message4Title {
            get {
                return ResourceManager.GetString("Message4Title", resourceCulture);
            }
        }
        
        internal static string Message5Title {
            get {
                return ResourceManager.GetString("Message5Title", resourceCulture);
            }
        }
        
        internal static string Message6Title {
            get {
                return ResourceManager.GetString("Message6Title", resourceCulture);
            }
        }
        
        internal static string Message7Title {
            get {
                return ResourceManager.GetString("Message7Title", resourceCulture);
            }
        }
        
        internal static string MessageBody {
            get {
                return ResourceManager.GetString("MessageBody", resourceCulture);
            }
        }
        
        internal static string Chat1Body {
            get {
                return ResourceManager.GetString("Chat1Body", resourceCulture);
            }
        }
        
        internal static string Chat2Body {
            get {
                return ResourceManager.GetString("Chat2Body", resourceCulture);
            }
        }
        
        internal static string Chat3Body {
            get {
                return ResourceManager.GetString("Chat3Body", resourceCulture);
            }
        }
        
        internal static string Chat4Body {
            get {
                return ResourceManager.GetString("Chat4Body", resourceCulture);
            }
        }
        
        internal static string Chat5Body {
            get {
                return ResourceManager.GetString("Chat5Body", resourceCulture);
            }
        }
        
        internal static string Chat6Body {
            get {
                return ResourceManager.GetString("Chat6Body", resourceCulture);
            }
        }
        
        internal static string Chat7Body {
            get {
                return ResourceManager.GetString("Chat7Body", resourceCulture);
            }
        }
        
        internal static string Chat8Body {
            get {
                return ResourceManager.GetString("Chat8Body", resourceCulture);
            }
        }
        
        internal static string Chat9Body {
            get {
                return ResourceManager.GetString("Chat9Body", resourceCulture);
            }
        }
        
        internal static string Chat10Body {
            get {
                return ResourceManager.GetString("Chat10Body", resourceCulture);
            }
        }
        
        internal static string Prod1Description {
            get {
                return ResourceManager.GetString("Prod1Description", resourceCulture);
            }
        }
        
        internal static string Prod1Name {
            get {
                return ResourceManager.GetString("Prod1Name", resourceCulture);
            }
        }
        
        internal static string Prod2Description {
            get {
                return ResourceManager.GetString("Prod2Description", resourceCulture);
            }
        }
        
        internal static string Prod2Name {
            get {
                return ResourceManager.GetString("Prod2Name", resourceCulture);
            }
        }
        
        internal static string Prod3Description {
            get {
                return ResourceManager.GetString("Prod3Description", resourceCulture);
            }
        }
        
        internal static string Prod3Name {
            get {
                return ResourceManager.GetString("Prod3Name", resourceCulture);
            }
        }
        
        internal static string Prod4Description {
            get {
                return ResourceManager.GetString("Prod4Description", resourceCulture);
            }
        }
        
        internal static string Prod4Name {
            get {
                return ResourceManager.GetString("Prod4Name", resourceCulture);
            }
        }
        
        internal static string Prod5Description {
            get {
                return ResourceManager.GetString("Prod5Description", resourceCulture);
            }
        }
        
        internal static string Prod5Name {
            get {
                return ResourceManager.GetString("Prod5Name", resourceCulture);
            }
        }
        
        internal static string Prod6Description {
            get {
                return ResourceManager.GetString("Prod6Description", resourceCulture);
            }
        }
        
        internal static string Prod6Name {
            get {
                return ResourceManager.GetString("Prod6Name", resourceCulture);
            }
        }
        
        internal static string Prod7Description {
            get {
                return ResourceManager.GetString("Prod7Description", resourceCulture);
            }
        }
        
        internal static string Prod7Name {
            get {
                return ResourceManager.GetString("Prod7Name", resourceCulture);
            }
        }
        
        internal static string Prod8Description {
            get {
                return ResourceManager.GetString("Prod8Description", resourceCulture);
            }
        }
        
        internal static string Prod8Name {
            get {
                return ResourceManager.GetString("Prod8Name", resourceCulture);
            }
        }
        
        internal static string TimelineEvent1Title {
            get {
                return ResourceManager.GetString("TimelineEvent1Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent1Description {
            get {
                return ResourceManager.GetString("TimelineEvent1Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent1When {
            get {
                return ResourceManager.GetString("TimelineEvent1When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent2Title {
            get {
                return ResourceManager.GetString("TimelineEvent2Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent2Description {
            get {
                return ResourceManager.GetString("TimelineEvent2Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent2When {
            get {
                return ResourceManager.GetString("TimelineEvent2When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent3Title {
            get {
                return ResourceManager.GetString("TimelineEvent3Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent3Description {
            get {
                return ResourceManager.GetString("TimelineEvent3Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent3When {
            get {
                return ResourceManager.GetString("TimelineEvent3When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent4Title {
            get {
                return ResourceManager.GetString("TimelineEvent4Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent4Description {
            get {
                return ResourceManager.GetString("TimelineEvent4Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent4When {
            get {
                return ResourceManager.GetString("TimelineEvent4When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent5Title {
            get {
                return ResourceManager.GetString("TimelineEvent5Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent5Description {
            get {
                return ResourceManager.GetString("TimelineEvent5Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent5When {
            get {
                return ResourceManager.GetString("TimelineEvent5When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent6Title {
            get {
                return ResourceManager.GetString("TimelineEvent6Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent6Description {
            get {
                return ResourceManager.GetString("TimelineEvent6Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent6When {
            get {
                return ResourceManager.GetString("TimelineEvent6When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent7Title {
            get {
                return ResourceManager.GetString("TimelineEvent7Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent7Description {
            get {
                return ResourceManager.GetString("TimelineEvent7Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent7When {
            get {
                return ResourceManager.GetString("TimelineEvent7When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent8Title {
            get {
                return ResourceManager.GetString("TimelineEvent8Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent8Description {
            get {
                return ResourceManager.GetString("TimelineEvent8Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent8When {
            get {
                return ResourceManager.GetString("TimelineEvent8When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent9Title {
            get {
                return ResourceManager.GetString("TimelineEvent9Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent9Description {
            get {
                return ResourceManager.GetString("TimelineEvent9Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent9When {
            get {
                return ResourceManager.GetString("TimelineEvent9When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent10Title {
            get {
                return ResourceManager.GetString("TimelineEvent10Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent10Description {
            get {
                return ResourceManager.GetString("TimelineEvent10Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent10When {
            get {
                return ResourceManager.GetString("TimelineEvent10When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent11Title {
            get {
                return ResourceManager.GetString("TimelineEvent11Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent11Description {
            get {
                return ResourceManager.GetString("TimelineEvent11Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent11When {
            get {
                return ResourceManager.GetString("TimelineEvent11When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent12Title {
            get {
                return ResourceManager.GetString("TimelineEvent12Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent12Description {
            get {
                return ResourceManager.GetString("TimelineEvent12Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent12When {
            get {
                return ResourceManager.GetString("TimelineEvent12When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent13Title {
            get {
                return ResourceManager.GetString("TimelineEvent13Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent13Description {
            get {
                return ResourceManager.GetString("TimelineEvent13Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent13When {
            get {
                return ResourceManager.GetString("TimelineEvent13When", resourceCulture);
            }
        }
        
        internal static string TimelineEvent14Title {
            get {
                return ResourceManager.GetString("TimelineEvent14Title", resourceCulture);
            }
        }
        
        internal static string TimelineEvent14Description {
            get {
                return ResourceManager.GetString("TimelineEvent14Description", resourceCulture);
            }
        }
        
        internal static string TimelineEvent14When {
            get {
                return ResourceManager.GetString("TimelineEvent14When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent1Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent1Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent1Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent1Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent1When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent1When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent2Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent2Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent2Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent2Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent2When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent2When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent3Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent3Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent3Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent3Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent3When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent3When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent4Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent4Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent4Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent4Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent4When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent4When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent5Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent5Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent5Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent5Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent5When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent5When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent6Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent6Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent6Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent6Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent6When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent6When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent7Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent7Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent7Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent7Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent7When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent7When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent8Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent8Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent8Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent8Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent8When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent8When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent9Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent9Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent9Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent9Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent9When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent9When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent10Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent10Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent10Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent10Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent10When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent10When", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent11Title {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent11Title", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent11Author {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent11Author", resourceCulture);
            }
        }
        
        internal static string DocumentTimelineEvent11When {
            get {
                return ResourceManager.GetString("DocumentTimelineEvent11When", resourceCulture);
            }
        }
        
        internal static string HighlightMovieTitle {
            get {
                return ResourceManager.GetString("HighlightMovieTitle", resourceCulture);
            }
        }
        
        internal static string HighlightMovieDescription {
            get {
                return ResourceManager.GetString("HighlightMovieDescription", resourceCulture);
            }
        }
        
        internal static string MovieSection1Title {
            get {
                return ResourceManager.GetString("MovieSection1Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie1Title {
            get {
                return ResourceManager.GetString("MovieSection1Movie1Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie1Seasons {
            get {
                return ResourceManager.GetString("MovieSection1Movie1Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie1Director {
            get {
                return ResourceManager.GetString("MovieSection1Movie1Director", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie1Plot {
            get {
                return ResourceManager.GetString("MovieSection1Movie1Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie1Cast {
            get {
                return ResourceManager.GetString("MovieSection1Movie1Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie2Title {
            get {
                return ResourceManager.GetString("MovieSection1Movie2Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie2Seasons {
            get {
                return ResourceManager.GetString("MovieSection1Movie2Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie2Director {
            get {
                return ResourceManager.GetString("MovieSection1Movie2Director", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie2Plot {
            get {
                return ResourceManager.GetString("MovieSection1Movie2Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie2Cast {
            get {
                return ResourceManager.GetString("MovieSection1Movie2Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie3Title {
            get {
                return ResourceManager.GetString("MovieSection1Movie3Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie3Seasons {
            get {
                return ResourceManager.GetString("MovieSection1Movie3Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie3Director {
            get {
                return ResourceManager.GetString("MovieSection1Movie3Director", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie3Plot {
            get {
                return ResourceManager.GetString("MovieSection1Movie3Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie3Cast {
            get {
                return ResourceManager.GetString("MovieSection1Movie3Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie4Title {
            get {
                return ResourceManager.GetString("MovieSection1Movie4Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie4Seasons {
            get {
                return ResourceManager.GetString("MovieSection1Movie4Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie4Director {
            get {
                return ResourceManager.GetString("MovieSection1Movie4Director", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie4Plot {
            get {
                return ResourceManager.GetString("MovieSection1Movie4Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie4Cast {
            get {
                return ResourceManager.GetString("MovieSection1Movie4Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie5Title {
            get {
                return ResourceManager.GetString("MovieSection1Movie5Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie5Seasons {
            get {
                return ResourceManager.GetString("MovieSection1Movie5Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie5Director {
            get {
                return ResourceManager.GetString("MovieSection1Movie5Director", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie5Plot {
            get {
                return ResourceManager.GetString("MovieSection1Movie5Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie5Cast {
            get {
                return ResourceManager.GetString("MovieSection1Movie5Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie6Title {
            get {
                return ResourceManager.GetString("MovieSection1Movie6Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie6Seasons {
            get {
                return ResourceManager.GetString("MovieSection1Movie6Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie6Director {
            get {
                return ResourceManager.GetString("MovieSection1Movie6Director", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie6Plot {
            get {
                return ResourceManager.GetString("MovieSection1Movie6Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie6Cast {
            get {
                return ResourceManager.GetString("MovieSection1Movie6Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie7Title {
            get {
                return ResourceManager.GetString("MovieSection1Movie7Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie7Seasons {
            get {
                return ResourceManager.GetString("MovieSection1Movie7Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie7Director {
            get {
                return ResourceManager.GetString("MovieSection1Movie7Director", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie7Plot {
            get {
                return ResourceManager.GetString("MovieSection1Movie7Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie7Cast {
            get {
                return ResourceManager.GetString("MovieSection1Movie7Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie8Title {
            get {
                return ResourceManager.GetString("MovieSection1Movie8Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie8Seasons {
            get {
                return ResourceManager.GetString("MovieSection1Movie8Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie8Director {
            get {
                return ResourceManager.GetString("MovieSection1Movie8Director", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie8Plot {
            get {
                return ResourceManager.GetString("MovieSection1Movie8Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie8Cast {
            get {
                return ResourceManager.GetString("MovieSection1Movie8Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie9Title {
            get {
                return ResourceManager.GetString("MovieSection1Movie9Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie9Seasons {
            get {
                return ResourceManager.GetString("MovieSection1Movie9Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie9Director {
            get {
                return ResourceManager.GetString("MovieSection1Movie9Director", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie9Plot {
            get {
                return ResourceManager.GetString("MovieSection1Movie9Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie9Cast {
            get {
                return ResourceManager.GetString("MovieSection1Movie9Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie10Title {
            get {
                return ResourceManager.GetString("MovieSection1Movie10Title", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie10Seasons {
            get {
                return ResourceManager.GetString("MovieSection1Movie10Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie10Director {
            get {
                return ResourceManager.GetString("MovieSection1Movie10Director", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie10Plot {
            get {
                return ResourceManager.GetString("MovieSection1Movie10Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection1Movie10Cast {
            get {
                return ResourceManager.GetString("MovieSection1Movie10Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection2Title {
            get {
                return ResourceManager.GetString("MovieSection2Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie1Title {
            get {
                return ResourceManager.GetString("MovieSection2Movie1Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie1Seasons {
            get {
                return ResourceManager.GetString("MovieSection2Movie1Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie1Director {
            get {
                return ResourceManager.GetString("MovieSection2Movie1Director", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie1Plot {
            get {
                return ResourceManager.GetString("MovieSection2Movie1Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie1Cast {
            get {
                return ResourceManager.GetString("MovieSection2Movie1Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie2Title {
            get {
                return ResourceManager.GetString("MovieSection2Movie2Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie2Seasons {
            get {
                return ResourceManager.GetString("MovieSection2Movie2Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie2Director {
            get {
                return ResourceManager.GetString("MovieSection2Movie2Director", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie2Plot {
            get {
                return ResourceManager.GetString("MovieSection2Movie2Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie2Cast {
            get {
                return ResourceManager.GetString("MovieSection2Movie2Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie3Title {
            get {
                return ResourceManager.GetString("MovieSection2Movie3Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie3Seasons {
            get {
                return ResourceManager.GetString("MovieSection2Movie3Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie3Director {
            get {
                return ResourceManager.GetString("MovieSection2Movie3Director", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie3Plot {
            get {
                return ResourceManager.GetString("MovieSection2Movie3Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie3Cast {
            get {
                return ResourceManager.GetString("MovieSection2Movie3Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie4Title {
            get {
                return ResourceManager.GetString("MovieSection2Movie4Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie4Seasons {
            get {
                return ResourceManager.GetString("MovieSection2Movie4Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie4Director {
            get {
                return ResourceManager.GetString("MovieSection2Movie4Director", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie4Plot {
            get {
                return ResourceManager.GetString("MovieSection2Movie4Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie4Cast {
            get {
                return ResourceManager.GetString("MovieSection2Movie4Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie5Title {
            get {
                return ResourceManager.GetString("MovieSection2Movie5Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie5Seasons {
            get {
                return ResourceManager.GetString("MovieSection2Movie5Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie5Director {
            get {
                return ResourceManager.GetString("MovieSection2Movie5Director", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie5Plot {
            get {
                return ResourceManager.GetString("MovieSection2Movie5Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie5Cast {
            get {
                return ResourceManager.GetString("MovieSection2Movie5Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie6Title {
            get {
                return ResourceManager.GetString("MovieSection2Movie6Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie6Seasons {
            get {
                return ResourceManager.GetString("MovieSection2Movie6Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie6Director {
            get {
                return ResourceManager.GetString("MovieSection2Movie6Director", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie6Plot {
            get {
                return ResourceManager.GetString("MovieSection2Movie6Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie6Cast {
            get {
                return ResourceManager.GetString("MovieSection2Movie6Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie7Title {
            get {
                return ResourceManager.GetString("MovieSection2Movie7Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie7Seasons {
            get {
                return ResourceManager.GetString("MovieSection2Movie7Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie7Director {
            get {
                return ResourceManager.GetString("MovieSection2Movie7Director", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie7Plot {
            get {
                return ResourceManager.GetString("MovieSection2Movie7Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie7Cast {
            get {
                return ResourceManager.GetString("MovieSection2Movie7Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie8Title {
            get {
                return ResourceManager.GetString("MovieSection2Movie8Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie8Seasons {
            get {
                return ResourceManager.GetString("MovieSection2Movie8Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie8Director {
            get {
                return ResourceManager.GetString("MovieSection2Movie8Director", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie8Plot {
            get {
                return ResourceManager.GetString("MovieSection2Movie8Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie8Cast {
            get {
                return ResourceManager.GetString("MovieSection2Movie8Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie9Title {
            get {
                return ResourceManager.GetString("MovieSection2Movie9Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie9Seasons {
            get {
                return ResourceManager.GetString("MovieSection2Movie9Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie9Director {
            get {
                return ResourceManager.GetString("MovieSection2Movie9Director", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie9Plot {
            get {
                return ResourceManager.GetString("MovieSection2Movie9Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie9Cast {
            get {
                return ResourceManager.GetString("MovieSection2Movie9Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie10Title {
            get {
                return ResourceManager.GetString("MovieSection2Movie10Title", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie10Seasons {
            get {
                return ResourceManager.GetString("MovieSection2Movie10Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie10Director {
            get {
                return ResourceManager.GetString("MovieSection2Movie10Director", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie10Plot {
            get {
                return ResourceManager.GetString("MovieSection2Movie10Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection2Movie10Cast {
            get {
                return ResourceManager.GetString("MovieSection2Movie10Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection3Title {
            get {
                return ResourceManager.GetString("MovieSection3Title", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie1Title {
            get {
                return ResourceManager.GetString("MovieSection3Movie1Title", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie1Seasons {
            get {
                return ResourceManager.GetString("MovieSection3Movie1Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie1Director {
            get {
                return ResourceManager.GetString("MovieSection3Movie1Director", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie1Plot {
            get {
                return ResourceManager.GetString("MovieSection3Movie1Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie1Cast {
            get {
                return ResourceManager.GetString("MovieSection3Movie1Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie2Title {
            get {
                return ResourceManager.GetString("MovieSection3Movie2Title", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie2Seasons {
            get {
                return ResourceManager.GetString("MovieSection3Movie2Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie2Director {
            get {
                return ResourceManager.GetString("MovieSection3Movie2Director", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie2Plot {
            get {
                return ResourceManager.GetString("MovieSection3Movie2Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie2Cast {
            get {
                return ResourceManager.GetString("MovieSection3Movie2Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie3Title {
            get {
                return ResourceManager.GetString("MovieSection3Movie3Title", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie3Seasons {
            get {
                return ResourceManager.GetString("MovieSection3Movie3Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie3Director {
            get {
                return ResourceManager.GetString("MovieSection3Movie3Director", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie3Plot {
            get {
                return ResourceManager.GetString("MovieSection3Movie3Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie3Cast {
            get {
                return ResourceManager.GetString("MovieSection3Movie3Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie4Title {
            get {
                return ResourceManager.GetString("MovieSection3Movie4Title", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie4Seasons {
            get {
                return ResourceManager.GetString("MovieSection3Movie4Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie4Director {
            get {
                return ResourceManager.GetString("MovieSection3Movie4Director", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie4Plot {
            get {
                return ResourceManager.GetString("MovieSection3Movie4Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie4Cast {
            get {
                return ResourceManager.GetString("MovieSection3Movie4Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie5Title {
            get {
                return ResourceManager.GetString("MovieSection3Movie5Title", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie5Seasons {
            get {
                return ResourceManager.GetString("MovieSection3Movie5Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie5Director {
            get {
                return ResourceManager.GetString("MovieSection3Movie5Director", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie5Plot {
            get {
                return ResourceManager.GetString("MovieSection3Movie5Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie5Cast {
            get {
                return ResourceManager.GetString("MovieSection3Movie5Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie6Title {
            get {
                return ResourceManager.GetString("MovieSection3Movie6Title", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie6Seasons {
            get {
                return ResourceManager.GetString("MovieSection3Movie6Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie6Director {
            get {
                return ResourceManager.GetString("MovieSection3Movie6Director", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie6Plot {
            get {
                return ResourceManager.GetString("MovieSection3Movie6Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection3Movie6Cast {
            get {
                return ResourceManager.GetString("MovieSection3Movie6Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection4Title {
            get {
                return ResourceManager.GetString("MovieSection4Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie1Title {
            get {
                return ResourceManager.GetString("MovieSection4Movie1Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie1Seasons {
            get {
                return ResourceManager.GetString("MovieSection4Movie1Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie1Director {
            get {
                return ResourceManager.GetString("MovieSection4Movie1Director", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie1Plot {
            get {
                return ResourceManager.GetString("MovieSection4Movie1Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie1Cast {
            get {
                return ResourceManager.GetString("MovieSection4Movie1Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie2Title {
            get {
                return ResourceManager.GetString("MovieSection4Movie2Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie2Seasons {
            get {
                return ResourceManager.GetString("MovieSection4Movie2Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie2Director {
            get {
                return ResourceManager.GetString("MovieSection4Movie2Director", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie2Plot {
            get {
                return ResourceManager.GetString("MovieSection4Movie2Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie2Cast {
            get {
                return ResourceManager.GetString("MovieSection4Movie2Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie3Title {
            get {
                return ResourceManager.GetString("MovieSection4Movie3Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie3Seasons {
            get {
                return ResourceManager.GetString("MovieSection4Movie3Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie3Director {
            get {
                return ResourceManager.GetString("MovieSection4Movie3Director", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie3Plot {
            get {
                return ResourceManager.GetString("MovieSection4Movie3Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie3Cast {
            get {
                return ResourceManager.GetString("MovieSection4Movie3Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie4Title {
            get {
                return ResourceManager.GetString("MovieSection4Movie4Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie4Seasons {
            get {
                return ResourceManager.GetString("MovieSection4Movie4Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie4Director {
            get {
                return ResourceManager.GetString("MovieSection4Movie4Director", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie4Plot {
            get {
                return ResourceManager.GetString("MovieSection4Movie4Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie4Cast {
            get {
                return ResourceManager.GetString("MovieSection4Movie4Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie5Title {
            get {
                return ResourceManager.GetString("MovieSection4Movie5Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie5Seasons {
            get {
                return ResourceManager.GetString("MovieSection4Movie5Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie5Director {
            get {
                return ResourceManager.GetString("MovieSection4Movie5Director", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie5Plot {
            get {
                return ResourceManager.GetString("MovieSection4Movie5Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie5Cast {
            get {
                return ResourceManager.GetString("MovieSection4Movie5Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie6Title {
            get {
                return ResourceManager.GetString("MovieSection4Movie6Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie6Seasons {
            get {
                return ResourceManager.GetString("MovieSection4Movie6Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie6Director {
            get {
                return ResourceManager.GetString("MovieSection4Movie6Director", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie6Plot {
            get {
                return ResourceManager.GetString("MovieSection4Movie6Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie6Cast {
            get {
                return ResourceManager.GetString("MovieSection4Movie6Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie7Title {
            get {
                return ResourceManager.GetString("MovieSection4Movie7Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie7Seasons {
            get {
                return ResourceManager.GetString("MovieSection4Movie7Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie7Director {
            get {
                return ResourceManager.GetString("MovieSection4Movie7Director", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie7Plot {
            get {
                return ResourceManager.GetString("MovieSection4Movie7Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie7Cast {
            get {
                return ResourceManager.GetString("MovieSection4Movie7Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie8Title {
            get {
                return ResourceManager.GetString("MovieSection4Movie8Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie8Seasons {
            get {
                return ResourceManager.GetString("MovieSection4Movie8Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie8Director {
            get {
                return ResourceManager.GetString("MovieSection4Movie8Director", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie8Plot {
            get {
                return ResourceManager.GetString("MovieSection4Movie8Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie8Cast {
            get {
                return ResourceManager.GetString("MovieSection4Movie8Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie9Title {
            get {
                return ResourceManager.GetString("MovieSection4Movie9Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie9Seasons {
            get {
                return ResourceManager.GetString("MovieSection4Movie9Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie9Director {
            get {
                return ResourceManager.GetString("MovieSection4Movie9Director", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie9Plot {
            get {
                return ResourceManager.GetString("MovieSection4Movie9Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie9Cast {
            get {
                return ResourceManager.GetString("MovieSection4Movie9Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie10Title {
            get {
                return ResourceManager.GetString("MovieSection4Movie10Title", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie10Seasons {
            get {
                return ResourceManager.GetString("MovieSection4Movie10Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie10Director {
            get {
                return ResourceManager.GetString("MovieSection4Movie10Director", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie10Plot {
            get {
                return ResourceManager.GetString("MovieSection4Movie10Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection4Movie10Cast {
            get {
                return ResourceManager.GetString("MovieSection4Movie10Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection5Title {
            get {
                return ResourceManager.GetString("MovieSection5Title", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie1Title {
            get {
                return ResourceManager.GetString("MovieSection5Movie1Title", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie1Seasons {
            get {
                return ResourceManager.GetString("MovieSection5Movie1Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie1Director {
            get {
                return ResourceManager.GetString("MovieSection5Movie1Director", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie1Plot {
            get {
                return ResourceManager.GetString("MovieSection5Movie1Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie1Cast {
            get {
                return ResourceManager.GetString("MovieSection5Movie1Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie2Title {
            get {
                return ResourceManager.GetString("MovieSection5Movie2Title", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie2Seasons {
            get {
                return ResourceManager.GetString("MovieSection5Movie2Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie2Director {
            get {
                return ResourceManager.GetString("MovieSection5Movie2Director", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie2Plot {
            get {
                return ResourceManager.GetString("MovieSection5Movie2Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie2Cast {
            get {
                return ResourceManager.GetString("MovieSection5Movie2Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie3Title {
            get {
                return ResourceManager.GetString("MovieSection5Movie3Title", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie3Seasons {
            get {
                return ResourceManager.GetString("MovieSection5Movie3Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie3Director {
            get {
                return ResourceManager.GetString("MovieSection5Movie3Director", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie3Plot {
            get {
                return ResourceManager.GetString("MovieSection5Movie3Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie3Cast {
            get {
                return ResourceManager.GetString("MovieSection5Movie3Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie4Title {
            get {
                return ResourceManager.GetString("MovieSection5Movie4Title", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie4Seasons {
            get {
                return ResourceManager.GetString("MovieSection5Movie4Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie4Director {
            get {
                return ResourceManager.GetString("MovieSection5Movie4Director", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie4Plot {
            get {
                return ResourceManager.GetString("MovieSection5Movie4Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie4Cast {
            get {
                return ResourceManager.GetString("MovieSection5Movie4Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie5Title {
            get {
                return ResourceManager.GetString("MovieSection5Movie5Title", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie5Seasons {
            get {
                return ResourceManager.GetString("MovieSection5Movie5Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie5Director {
            get {
                return ResourceManager.GetString("MovieSection5Movie5Director", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie5Plot {
            get {
                return ResourceManager.GetString("MovieSection5Movie5Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie5Cast {
            get {
                return ResourceManager.GetString("MovieSection5Movie5Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie6Title {
            get {
                return ResourceManager.GetString("MovieSection5Movie6Title", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie6Seasons {
            get {
                return ResourceManager.GetString("MovieSection5Movie6Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie6Director {
            get {
                return ResourceManager.GetString("MovieSection5Movie6Director", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie6Plot {
            get {
                return ResourceManager.GetString("MovieSection5Movie6Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie6Cast {
            get {
                return ResourceManager.GetString("MovieSection5Movie6Cast", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie7Title {
            get {
                return ResourceManager.GetString("MovieSection5Movie7Title", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie7Seasons {
            get {
                return ResourceManager.GetString("MovieSection5Movie7Seasons", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie7Director {
            get {
                return ResourceManager.GetString("MovieSection5Movie7Director", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie7Plot {
            get {
                return ResourceManager.GetString("MovieSection5Movie7Plot", resourceCulture);
            }
        }
        
        internal static string MovieSection5Movie7Cast {
            get {
                return ResourceManager.GetString("MovieSection5Movie7Cast", resourceCulture);
            }
        }
        
        internal static string DasboardCard1Title {
            get {
                return ResourceManager.GetString("DasboardCard1Title", resourceCulture);
            }
        }
        
        internal static string DasboardCard1Body {
            get {
                return ResourceManager.GetString("DasboardCard1Body", resourceCulture);
            }
        }
        
        internal static string DasboardCard1Section {
            get {
                return ResourceManager.GetString("DasboardCard1Section", resourceCulture);
            }
        }
        
        internal static string DasboardCard1Author {
            get {
                return ResourceManager.GetString("DasboardCard1Author", resourceCulture);
            }
        }
        
        internal static string DasboardCard2Title {
            get {
                return ResourceManager.GetString("DasboardCard2Title", resourceCulture);
            }
        }
        
        internal static string DasboardCard2Body {
            get {
                return ResourceManager.GetString("DasboardCard2Body", resourceCulture);
            }
        }
        
        internal static string DasboardCard2Section {
            get {
                return ResourceManager.GetString("DasboardCard2Section", resourceCulture);
            }
        }
        
        internal static string DasboardCard2Author {
            get {
                return ResourceManager.GetString("DasboardCard2Author", resourceCulture);
            }
        }
        
        internal static string DasboardCard3Title {
            get {
                return ResourceManager.GetString("DasboardCard3Title", resourceCulture);
            }
        }
        
        internal static string DasboardCard3Body {
            get {
                return ResourceManager.GetString("DasboardCard3Body", resourceCulture);
            }
        }
        
        internal static string DasboardCard3Section {
            get {
                return ResourceManager.GetString("DasboardCard3Section", resourceCulture);
            }
        }
        
        internal static string DasboardCard3Author {
            get {
                return ResourceManager.GetString("DasboardCard3Author", resourceCulture);
            }
        }
        
        internal static string DasboardCard4Title {
            get {
                return ResourceManager.GetString("DasboardCard4Title", resourceCulture);
            }
        }
        
        internal static string DasboardCard4Body {
            get {
                return ResourceManager.GetString("DasboardCard4Body", resourceCulture);
            }
        }
        
        internal static string DasboardCard4Section {
            get {
                return ResourceManager.GetString("DasboardCard4Section", resourceCulture);
            }
        }
        
        internal static string DasboardCard4Author {
            get {
                return ResourceManager.GetString("DasboardCard4Author", resourceCulture);
            }
        }
        
        internal static string DasboardCard5Title {
            get {
                return ResourceManager.GetString("DasboardCard5Title", resourceCulture);
            }
        }
        
        internal static string DasboardCard5Body {
            get {
                return ResourceManager.GetString("DasboardCard5Body", resourceCulture);
            }
        }
        
        internal static string DasboardCard5Section {
            get {
                return ResourceManager.GetString("DasboardCard5Section", resourceCulture);
            }
        }
        
        internal static string DasboardCard5Author {
            get {
                return ResourceManager.GetString("DasboardCard5Author", resourceCulture);
            }
        }
        
        internal static string DasboardCard6Title {
            get {
                return ResourceManager.GetString("DasboardCard6Title", resourceCulture);
            }
        }
        
        internal static string DasboardCard6Body {
            get {
                return ResourceManager.GetString("DasboardCard6Body", resourceCulture);
            }
        }
        
        internal static string DasboardCard6Section {
            get {
                return ResourceManager.GetString("DasboardCard6Section", resourceCulture);
            }
        }
        
        internal static string DasboardCard6Author {
            get {
                return ResourceManager.GetString("DasboardCard6Author", resourceCulture);
            }
        }
        
        internal static string DasboardCard7Title {
            get {
                return ResourceManager.GetString("DasboardCard7Title", resourceCulture);
            }
        }
        
        internal static string DasboardCard7Body {
            get {
                return ResourceManager.GetString("DasboardCard7Body", resourceCulture);
            }
        }
        
        internal static string DasboardCard7Section {
            get {
                return ResourceManager.GetString("DasboardCard7Section", resourceCulture);
            }
        }
        
        internal static string DasboardCard7Author {
            get {
                return ResourceManager.GetString("DasboardCard7Author", resourceCulture);
            }
        }
        
        internal static string DasboardCard8Title {
            get {
                return ResourceManager.GetString("DasboardCard8Title", resourceCulture);
            }
        }
        
        internal static string DasboardCard8Body {
            get {
                return ResourceManager.GetString("DasboardCard8Body", resourceCulture);
            }
        }
        
        internal static string DasboardCard8Section {
            get {
                return ResourceManager.GetString("DasboardCard8Section", resourceCulture);
            }
        }
        
        internal static string DasboardCard8Author {
            get {
                return ResourceManager.GetString("DasboardCard8Author", resourceCulture);
            }
        }
        
        internal static string DasboardCard9Title {
            get {
                return ResourceManager.GetString("DasboardCard9Title", resourceCulture);
            }
        }
        
        internal static string DasboardCard9Body {
            get {
                return ResourceManager.GetString("DasboardCard9Body", resourceCulture);
            }
        }
        
        internal static string DasboardCard9Section {
            get {
                return ResourceManager.GetString("DasboardCard9Section", resourceCulture);
            }
        }
        
        internal static string DasboardCard9Author {
            get {
                return ResourceManager.GetString("DasboardCard9Author", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem1Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem1Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem2Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem2Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem3Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem3Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem4Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem4Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem5Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem5Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem6Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem6Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem7Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem7Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem7Body {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem7Body", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem8Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem8Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem9Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem9Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem9Body {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem9Body", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem10Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem10Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem10Body {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem10Body", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem11Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem11Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem12Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem12Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem12Body {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem12Body", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem13Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem13Title", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem13Body {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem13Body", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTileItem14Title {
            get {
                return ResourceManager.GetString("DashboardMultipleTileItem14Title", resourceCulture);
            }
        }
    }
}
